apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: test-dev
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30144